### ISSUE TITLE
Macros

### ISSUE THREAD

**Issue by m-bra** [Kev/clang-flags#5]
Would be nice if the package would expand some macros, e.g. the file being edited, the path to that file, the project path...

**Comment by Kev** [comment]
Can you explain what you want here, please? This is just a helper library that gets called by Atom plugins, which have that information available to them.

**Comment by m-bra** [comment]
For example, when you have the clang complete file, you can write `-I"%FILE%/include"`, and when this library reads the file, it substitutes `%FILE%` with the file path being edited. However, I see now, that this library should not implement something like that, that's the problem of the plugin using this lib. Sorry :smile:
